### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by mitar**
This will be a branch/pull request of various fixes I am working on. Sorry, but some things are a bit hard to make as a separate pull request. But I will make separate commits, so you can at least cherry-pick them.

### CODE REVIEW

**Comment by cunneen** [comment]
Awesome, thanks! I'll merge these when I some time to look through them. As you're no doubt aware, this is just a fork of the bootstrap version with mostly CSS changes. Most of the issues you've raised have been inherited but do need fixing. I have added some Roles-based stuff, but that will soon be put into a separate package; the behaviour as it relates to this package is documented in the Readme.

**Comment by cunneen** [comment]
I merged all of these except 7c595ff and d8a15e8 : I want to keep translation enabled, this also enables the "Full Name" field label to be easily overridden (in a separate `t9n/en.coffee` file elsewhere in your application). Thanks again for sharing these changes!

**Comment by mitar** [comment]
7c595ff42a544d5e578fbd76800e69fd7433d205 allows translation to be enabled, it just unifies the translation key to lower case with the rest of the app.

d8a15e8ab5d4d17b972cab0da1501bdb7a2ec74c still allows "full name" to be used, but it is not necessary that it is full name based on current use of this field.

**Comment by cunneen** [comment]
Oops, my bad: I _did_ merge 7c595ff ; It was 7a0c35c that I didn't merge (that translates the role name).

**Comment by mitar** [comment]
Oh, the problem with that one was that if the role name was not having a translation, then t9n ads some prefix for some reason. So it does not just pass it through.

**Comment by cunneen** [comment]
Yes, I understand. But removing the translation is not a solution: we have
users with different languages so the translation is there for a reason!
Providing translations for roles is simple enough; otherwise you could
write a helper to check whether a translation exists.

An alternative is to override the T9n prefix and suffix:

```

T9n.missingPrefix = ">"
T9n.missingPostfix = "<"

```

**Comment by mitar** [comment]
BTW, it seems you did merge 7a0c35cb9fe7385a41920e10bcc52815cc7defab.

**Pull request merged**
